theme: jekyll-theme-minimal
title: Matthias Katerbow
logo: user.png
description:  <p>I'm a science manager at German Research Foundation focusing on e-research technologies and Digital Turn in Science and Research. This is my personal website, views are my own.</p> <p class="view"><a href="https://twitter.com/katerbow" target="_blank">View My Twitter Profile</a></p>
