theme: jekyll-theme-minimal
title: Matthias Katerbow
logo: user.png
description:  <p>I'm a science manager at <a href="http://www.dfg.de" target="_blank">German Research Foundation</a> focusing on e-research-technologies and the Digital Turn in Science and Research. This is my personal website, views are my own.</p>
